# Generated by Django 4.2 on 2023-04-05 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.CharField(choices=[('USER', 'User'), ('MERCHANT', 'Merchant'), ('CARD', 'Card'), ('BANK', 'Bank')], max_length=32)),
                ('avatar_name', models.CharField(max_length=32)),
                ('avatar_icon', models.BinaryField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(max_length=32)),
                ('version', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=256)),
                ('digital_signature', models.BinaryField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, max_length=256, null=True)),
                ('device_info', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DigitalCurrencyAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=256)),
                ('balance', models.DecimalField(decimal_places=8, max_digits=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OBPAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, max_length=256, null=True)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.CharField(choices=[('TRANSFER', 'Transfer digital currency tokens'), ('PAYMENT', 'Payment using digital currency tokens'), ('REQUEST', 'Payment request using digital currency tokens'), ('REFUND', 'Payment refund using digital currency tokens'), ('WITHDRAWAL', 'Withdrawal of digital currency tokens'), ('DEPOSIT', 'Deposit of digital currency tokens')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=32)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('from_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user_id', to='BackendAPI.accountholder')),
                ('to_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_id', to='BackendAPI.accountholder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DigitalCurrencyToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, max_length=256, null=True)),
                ('token_value', models.DecimalField(decimal_places=8, max_digits=32)),
                ('token', models.BinaryField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BackendAPI.digitalcurrencyaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CryptographicMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[('RSA_2048_PUB', 'Public RSA key'), ('RSA_2048_PRV', 'Private RSA key'), ('AES_256_GCM', '256 bits AES key GCM mode')], max_length=32)),
                ('value', models.BinaryField()),
                ('state', models.CharField(choices=[('PENDING', 'Cryptographic material generation pending'), ('ACTIVE', 'Cryptographic material active'), ('INACTIVE', 'Cryptographic material inactive'), ('REVOKED', 'Cryptographic material revoked')], max_length=32)),
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BackendAPI.applicationinstance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationProvisioningToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, max_length=256, null=True)),
                ('state', models.CharField(choices=[('PENDING', 'Provisioning token issued, provisioning pending'), ('PROVISIONED', 'Application instance provisioning successful'), ('FAILED', 'Application instance provisioning failed')], max_length=32)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackendAPI.application')),
                ('holder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BackendAPI.accountholder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='applicationinstance',
            name='token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BackendAPI.applicationprovisioningtoken'),
        ),
        migrations.AddField(
            model_name='accountholder',
            name='dc_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BackendAPI.digitalcurrencyaccount'),
        ),
        migrations.AddField(
            model_name='accountholder',
            name='obp_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BackendAPI.obpaccount'),
        ),
        migrations.AddField(
            model_name='accountholder',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
