/**
 * MobileWalletPOT
 * Mobile Wallet POT backend API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param session_id
 * @param &#x60;data&#x60; 
 */
data class ProcessingData (

    val session_id: kotlin.String,
    val `data`: kotlin.String
) {
}