/**
 * MobileWalletPOT
 * Mobile Wallet POT backend API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.SessionDataType

/**
 * 
 * @param sessionId 
 * @param dataType 
 */
data class RequestSessionData (

    val sessionId: kotlin.String,
    val dataType: SessionDataType
) {
}