/**
 * MobileWalletPOT
 * Mobile Wallet POT backend API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * An enumeration.
 * Values: NONE,TXPENDINGLIST,FAVHOLDERSLIST,FAVMERCHANTSLIST,FAVINTERMEDIARIESLIST
 */
enum class SessionDataType(val value: kotlin.String){
    NONE("none"),// :/
    TXPENDINGLIST("tx_pending_list"),// :/
    FAVHOLDERSLIST("fav_holders_list"),// :/
    FAVMERCHANTSLIST("fav_merchants_list"),// :/
    FAVINTERMEDIARIESLIST("fav_intermediaries_list");// :/
}