/**
 * MobileWalletPOT
 * Mobile Wallet POT backend API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param loc 
 * @param msg 
 * @param type 
 */
data class ValidationError (

    val loc: kotlin.Array<AnyOfValidationErrorLocItems>,
    val msg: kotlin.String,
    val type: kotlin.String
) {
}