//
// OnlineTransactionData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OnlineTransactionData: Codable {

    public var token: String
    public var data: String

    public init(token: String, data: String) {
        self.token = token
        self.data = data
    }


}
