//
// ProcessingData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ProcessingData: Codable {

    public var sessionId: String
    public var data: String

    public init(sessionId: String, data: String) {
        self.sessionId = sessionId
        self.data = data
    }

    public enum CodingKeys: String, CodingKey { 
        case sessionId = "session_id"
        case data
    }

}
