//
// RequestSessionData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RequestSessionData: Codable {

    public var sessionId: String
    public var dataType: SessionDataType

    public init(sessionId: String, dataType: SessionDataType) {
        self.sessionId = sessionId
        self.dataType = dataType
    }

    public enum CodingKeys: String, CodingKey { 
        case sessionId = "session_id"
        case dataType = "data_type"
    }

}
