//
// SessionDataType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An enumeration. */
public enum SessionDataType: String, Codable {
    case _none = "none"
    case txPendingList = "tx_pending_list"
    case favHoldersList = "fav_holders_list"
    case favMerchantsList = "fav_merchants_list"
    case favIntermediariesList = "fav_intermediaries_list"
}