# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'sk_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  target 'sk_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sk_appUITests' do
    # Pods for testing
  end

  pod "Alamofire", "~> 4.9.0"

end

