from dataclasses import dataclass, field


@dataclass
class OBPView:
	# View object class
	id: str
	short_name: str
	description: str = ""
	metadata_view: str = ""
	is_public: bool = False
	is_system: bool = False
	alias: str = 'No'
	hide_metadata_if_alias_used: bool = False
	can_grant_access_to_views: list[str] = field(default_factory=list)
	can_revoke_access_to_views: list[str] = field(default_factory=list)
	can_add_comment: bool = False
	can_add_corporate_location: bool = False
	can_add_image: bool = False
	can_add_image_url: bool = False
	can_add_more_info: bool = False
	can_add_open_corporates_url: bool = False
	can_add_physical_location: bool = False
	can_add_private_alias: bool = False
	can_add_public_alias: bool = False
	can_add_tag: bool = False
	can_add_url: bool = False
	can_add_where_tag: bool = False
	can_delete_comment: bool = False
	can_add_counterparty: bool = False
	can_delete_corporate_location: bool = False
	can_delete_image: bool = False
	can_delete_physical_location: bool = False
	can_delete_tag: bool = False
	can_delete_where_tag: bool = False
	can_edit_owner_comment: bool = False
	can_see_bank_account_balance: bool = False
	can_query_available_funds: bool = False
	can_see_bank_account_bank_name: bool = False
	can_see_bank_account_currency: bool = False
	can_see_bank_account_iban: bool = False
	can_see_bank_account_label: bool = False
	can_see_bank_account_national_identifier: bool = False
	can_see_bank_account_number: bool = False
	can_see_bank_account_owners: bool = False
	can_see_bank_account_swift_bic: bool = False
	can_see_bank_account_type: bool = False
	can_see_comments: bool = False
	can_see_corporate_location: bool = False
	can_see_image_url: bool = False
	can_see_images: bool = False
	can_see_more_info: bool = False
	can_see_open_corporates_url: bool = False
	can_see_other_account_bank_name: bool = False
	can_see_other_account_iban: bool = False
	can_see_other_account_kind: bool = False
	can_see_other_account_metadata: bool = False
	can_see_other_account_national_identifier: bool = False
	can_see_other_account_number: bool = False
	can_see_other_account_swift_bic: bool = False
	can_see_owner_comment: bool = False
	can_see_physical_location: bool = False
	can_see_private_alias: bool = False
	can_see_public_alias: bool = False
	can_see_tags: bool = False
	can_see_transaction_amount: bool = False
	can_see_transaction_balance: bool = False
	can_see_transaction_currency: bool = False
	can_see_transaction_description: bool = False
	can_see_transaction_finish_date: bool = False
	can_see_transaction_metadata: bool = False
	can_see_transaction_other_bank_account: bool = False
	can_see_transaction_start_date: bool = False
	can_see_transaction_this_bank_account: bool = False
	can_see_transaction_type: bool = False
	can_see_url: bool = False
	can_see_where_tag: bool = False
	can_see_bank_routing_scheme: bool = False
	can_see_bank_routing_address: bool = False
	can_see_bank_account_routing_scheme: bool = False
	can_see_bank_account_routing_address: bool = False
	can_see_other_bank_routing_scheme: bool = False
	can_see_other_bank_routing_address: bool = False
	can_see_other_account_routing_scheme: bool = False
	can_see_other_account_routing_address: bool = False
	can_add_transaction_request_to_own_account: bool = False
	can_add_transaction_request_to_any_account: bool = False
	can_see_bank_account_credit_limit: bool = False
	can_create_direct_debit: bool = False
	can_create_standing_order: bool = False
